import { useEffect, useState } from 'react';
import i18n from '@/shared/config/i18n';
import { loadLabConfig } from '@/entities/runtime-config/api/load-lab-config';
import type { LabRuntimeConfig } from './lab-runtime-config.schema';

interface LabConfigState {
  config: LabRuntimeConfig | null;
  error: string | null;
  isLoading: boolean;
}

/**
 * Loads the runtime configuration generated by the gateway bootstrap.
 */
export function useLabConfig(): LabConfigState {
  const [state, setState] = useState<LabConfigState>({
    config: null,
    error: null,
    isLoading: true
  });

  useEffect(() => {
    let isCurrent = true;

    void loadLabConfig()
      .then((config) => {
        if (!isCurrent) {
          return;
        }

        setState({
          config,
          error: null,
          isLoading: false
        });
      })
      .catch((error: unknown) => {
        if (!isCurrent) {
          return;
        }

        setState({
          config: null,
          error: error instanceof Error ? error.message : i18n.t('errors.invalidRuntimeConfig'),
          isLoading: false
        });
      });

    return () => {
      isCurrent = false;
    };
  }, []);

  return state;
}
