import i18n from '@/shared/config/i18n';

const BRIEFING_REQUEST_OPTIONS: RequestInit = {
  cache: 'no-store'
};

/**
 * Fetches a markdown briefing generated by the gateway bootstrap.
 */
export async function loadBriefing(path: string): Promise<string> {
  const response = await fetch(path, BRIEFING_REQUEST_OPTIONS);
  if (!response.ok) {
    throw new Error(
      i18n.t('errors.briefingHttpStatus', {
        status: response.status
      })
    );
  }

  return response.text();
}
