/**
 * Runtime configuration generated by the gateway startup process.
 */
export interface LabRuntimeConfig {
  features: {
    aiLlmEnabled: boolean;
    aiImageEnabled: boolean;
    workbenchEnabled: boolean;
  };
  assets: {
    certificateUrl: string;
  };
  content: {
    networkMapPath: string;
  };
  lab: {
    localUrl: string;
    name: string;
    publicUrl: string;
  };
  services: {
    gitea: {
      rootEmail: string;
      rootPassword: string;
      rootUsername: string;
      url: string;
    };
    n8n: {
      ownerEmail: string;
      ownerName: string;
      ownerPassword: string;
      url: string;
    };
    ollama: {
      gatewayPassword: string;
      gatewayUser: string;
      url: string;
    };
    invokeAi: {
      briefingPath: string;
      gatewayPassword: string;
      gatewayUser: string;
      modelRepo: string;
      modelRevision: string;
      modelTitle: string;
      url: string;
    };
    swarmUi: {
      briefingPath: string;
      gatewayPassword: string;
      gatewayUser: string;
      modelFile: string;
      modelRepo: string;
      modelRevision: string;
      modelTitle: string;
      url: string;
    };
    fooocus: {
      briefingPath: string;
      gatewayPassword: string;
      gatewayUser: string;
      url: string;
    };
    openWebUi: {
      rootEmail: string;
      rootName: string;
      rootPassword: string;
      url: string;
    };
  };
  workbenches: {
    ai: {
      briefingPath: string;
      password: string;
      url: string;
    };
    cpp: {
      briefingPath: string;
      password: string;
      url: string;
    };
    node: {
      briefingPath: string;
      password: string;
      url: string;
    };
    postgres: {
      briefingPath: string;
      database: string;
      host: string;
      internalHost: string;
      internalPort: string;
      password: string;
      port: string;
      superuser: string;
    };
    python: {
      briefingPath: string;
      password: string;
      url: string;
    };
  };
}
