#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve the repository root once so every git/fs command works from a stable base.
const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGE_JSON_PATH = path.join(ROOT_DIR, 'package.json');
const PACKAGE_LOCK_PATH = path.join(ROOT_DIR, 'package-lock.json');
const README_PATH = path.join(ROOT_DIR, 'README.md');
const CHANGELOG_PATH = path.join(ROOT_DIR, 'CHANGELOG.md');
const ENV_DIR = path.join(ROOT_DIR, 'env');

const cliArgs = process.argv.slice(2);

if (cliArgs.length > 0) {
  console.error('Usage: npm run set:version');
  console.error('This command is automatic and does not accept arguments or flags.');
  process.exit(1);
}

const semverRegex = /^\d+\.\d+\.\d+$/;
const tagVersionRegex = /^v?(\d+)\.(\d+)\.(\d+)(?:[-+][A-Za-z0-9.-]+)?$/;
const changelogHeader = [
  '# Changelog',
  '',
  'Generated by `npm run set:version`.',
  'The local changelog is rebuilt from the available `v*` release tags and the current `HEAD` range.',
  'The script does not create tags locally.',
  ''
].join('\n');

const runGitCapture = (args) =>
  execFileSync('git', args, {
    cwd: ROOT_DIR,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  }).trim();

const runGit = (args) => {
  try {
    execFileSync('git', args, { cwd: ROOT_DIR, stdio: 'inherit' });
  } catch (error) {
    console.warn(`[set:version] Failed to run "git ${args.join(' ')}": ${error?.message ?? error}`);
  }
};

const hasStagedChanges = () => {
  try {
    execFileSync('git', ['diff', '--cached', '--quiet', '--exit-code'], {
      cwd: ROOT_DIR,
      stdio: 'ignore'
    });
    return false;
  } catch (error) {
    return error && typeof error === 'object' && 'status' in error && error.status === 1;
  }
};

// Interpret the commit subject using Conventional Commits semantics.
const bumpType = (commitSubject) => {
  const match = commitSubject.match(/^([a-z]+)(\(.+\))?(!)?:/);
  const isConventional = Boolean(match);
  const type = isConventional ? match[1] : null;
  const hasBang = isConventional && Boolean(match[3]);
  const hasBreakingMarker = /BREAKING CHANGE/.test(commitSubject);
  return {
    type,
    isConventional,
    breaking: hasBang || hasBreakingMarker
  };
};

const parseVersion = (value) => {
  const match = value.trim().match(tagVersionRegex);
  if (!match) {
    throw new Error(`Unsupported semantic version format: ${value}`);
  }

  return {
    major: Number(match[1]),
    minor: Number(match[2]),
    patch: Number(match[3])
  };
};

const formatVersion = ({ major, minor, patch }) => `${major}.${minor}.${patch}`;

const getRootCommit = () =>
  runGitCapture(['rev-list', '--max-parents=0', 'HEAD']).split(/\s+/).filter(Boolean)[0];

const ROOT_COMMIT = getRootCommit();

const getReleaseTags = () => {
  const tags = runGitCapture(['tag', '--list', 'v*', '--sort=v:refname']);
  if (!tags) {
    return [];
  }

  return tags
    .split(/\r?\n/)
    .map((tag) => tag.trim())
    .filter((tag) => tagVersionRegex.test(tag));
};

const getCommitLogEntries = (baseRef, targetRef = 'HEAD') => {
  const range = `${baseRef}..${targetRef}`;
  const output = runGitCapture(['log', '--no-merges', '--format=%H|%s', '--reverse', range]);
  if (!output) {
    return [];
  }

  return output
    .split(/\r?\n/)
    .map((line) => {
      const separatorIndex = line.indexOf('|');
      if (separatorIndex === -1) {
        return null;
      }

      return {
        sha: line.slice(0, separatorIndex).trim(),
        subject: line.slice(separatorIndex + 1).trim()
      };
    })
    .filter(Boolean);
};

const resolveReleaseBase = () => {
  const releaseTags = getReleaseTags();
  const latestTag = releaseTags.at(-1) ?? null;
  if (latestTag) {
    return {
      releaseTags,
      baseRef: latestTag,
      baseTag: latestTag,
      baseVersion: parseVersion(latestTag)
    };
  }

  return {
    releaseTags,
    baseRef: ROOT_COMMIT,
    baseTag: null,
    baseVersion: { major: 0, minor: 0, patch: 0 }
  };
};

const computeNextVersion = ({ baseVersion, commitEntries }) => {
  let { major, minor, patch } = baseVersion;

  for (const entry of commitEntries) {
    const message = entry.subject.trim();
    if (!message) {
      continue;
    }

    const { type, isConventional, breaking } = bumpType(message);

    if (!isConventional) {
      if (/Revert "(feat|fix|perf|docs|style|refactor|test|chore|build|ci)/.test(message)) {
        const fallback = message.match(
          /Revert "(feat|fix|perf|docs|style|refactor|test|chore|build|ci)/
        )?.[1];
        if (fallback) {
          if (fallback === 'feat') {
            minor += 1;
            patch = 0;
          } else if (['fix', 'perf'].includes(fallback)) {
            patch += 1;
          }
        }
      }
      continue;
    }

    if (breaking) {
      major += 1;
      minor = 0;
      patch = 0;
      continue;
    }

    switch (type) {
      case 'feat': {
        minor += 1;
        patch = 0;
        break;
      }
      case 'fix':
      case 'perf':
      case 'docs':
      case 'style':
      case 'refactor':
      case 'test':
      case 'chore':
      case 'build':
      case 'ci': {
        patch += 1;
        break;
      }
      default: {
        break;
      }
    }
  }

  return formatVersion({ major, minor, patch });
};

const getBucketKey = (subject) => {
  const typePrefix = subject.split(':', 1)[0] ?? '';
  const type = typePrefix.split('(', 1)[0].trim().toLowerCase();

  switch (type) {
    case 'feat':
    case 'feature':
      return 'features';
    case 'fix':
    case 'bugfix':
    case 'hotfix':
      return 'fixes';
    case 'perf':
    case 'performance':
      return 'performance';
    case 'refactor':
    case 'refactoring':
      return 'refactor';
    case 'docs':
    case 'doc':
      return 'docs';
    case 'test':
    case 'tests':
      return 'tests';
    case 'chore':
    case 'ci':
    case 'build':
    case 'builds':
      return 'chore';
    case 'revert':
      return 'reverts';
    default:
      return 'other';
  }
};

const getDisplaySubject = (subject) => {
  if (!subject.includes(': ')) {
    return subject;
  }

  const prefix = subject.slice(0, subject.indexOf(':'));
  const message = subject.slice(subject.indexOf(': ') + 2);
  const scopeMatch = prefix.match(/\((.+)\)/);
  if (!scopeMatch?.[1]) {
    return message;
  }

  return `[${scopeMatch[1]}] ${message}`;
};

const getReferenceDate = (ref, fallbackDate = new Date().toISOString().slice(0, 10)) => {
  try {
    const resolved = runGitCapture(['log', '-1', '--format=%cs', ref]);
    return resolved || fallbackDate;
  } catch {
    return fallbackDate;
  }
};

const buildChangelogSection = ({
  version,
  baseRef,
  targetRef,
  releaseTag,
  commitEntries,
  referenceDate,
  isCurrent
}) => {
  const buckets = new Map([
    ['features', []],
    ['fixes', []],
    ['refactor', []],
    ['performance', []],
    ['docs', []],
    ['tests', []],
    ['chore', []],
    ['reverts', []],
    ['other', []]
  ]);

  for (const entry of commitEntries) {
    if (!entry.subject) {
      continue;
    }

    const bucketKey = getBucketKey(entry.subject);
    const displaySubject = getDisplaySubject(entry.subject);
    buckets.get(bucketKey)?.push(`- ${displaySubject} (\`${entry.sha.slice(0, 7)}\`)`);
  }

  const lines = [`## v${version} - ${referenceDate}`, ''];

  if (releaseTag) {
    lines.push(`- Release tag: \`${releaseTag}\``);
  } else if (isCurrent) {
    lines.push('- Release source: local versioning run');
  }

  if (baseRef === ROOT_COMMIT) {
    lines.push(`- Base commit: \`${baseRef.slice(0, 7)}\``);
  } else {
    lines.push(`- Base ref: \`${baseRef}\``);
  }
  lines.push(`- Range: \`${baseRef}..${targetRef}\``);
  lines.push(`- Included commits: ${commitEntries.length}`);
  lines.push('');

  const sections = [
    ['Features', 'features'],
    ['Fix', 'fixes'],
    ['Refactor', 'refactor'],
    ['Performance', 'performance'],
    ['Documentation', 'docs'],
    ['Test', 'tests'],
    ['CI / Maintenance', 'chore'],
    ['Revert', 'reverts'],
    ['Other', 'other']
  ];

  let wroteContent = false;
  for (const [title, key] of sections) {
    const entries = buckets.get(key) ?? [];
    if (!entries.length) {
      continue;
    }

    wroteContent = true;
    lines.push(`### ${title} (${entries.length})`, '');
    lines.push(...entries, '');
  }

  if (!wroteContent) {
    lines.push('No relevant commits were detected for this release.', '');
  }

  return `${lines.join('\n').trim()}\n`;
};

const buildHistoricalChangelog = ({ currentVersion, releaseTags }) => {
  const sections = [];
  const latestTag = releaseTags.at(-1) ?? null;
  const currentEntries = getCommitLogEntries(latestTag ?? ROOT_COMMIT, 'HEAD');

  if (
    !latestTag ||
    currentEntries.length > 0 ||
    currentVersion !== formatVersion(parseVersion(latestTag))
  ) {
    sections.push(
      buildChangelogSection({
        version: currentVersion,
        baseRef: latestTag ?? ROOT_COMMIT,
        targetRef: 'HEAD',
        releaseTag: null,
        commitEntries: currentEntries,
        referenceDate: new Date().toISOString().slice(0, 10),
        isCurrent: true
      })
    );
  }

  for (let index = releaseTags.length - 1; index >= 0; index -= 1) {
    const releaseTag = releaseTags[index];
    const baseRef = index === 0 ? ROOT_COMMIT : releaseTags[index - 1];
    const commitEntries = getCommitLogEntries(baseRef, releaseTag);

    sections.push(
      buildChangelogSection({
        version: formatVersion(parseVersion(releaseTag)),
        baseRef,
        targetRef: releaseTag,
        releaseTag,
        commitEntries,
        referenceDate: getReferenceDate(releaseTag),
        isCurrent: false
      })
    );
  }

  return `${changelogHeader}${sections.join('\n').trim()}\n`;
};

const updatePackageJson = (version) => {
  const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8'));
  packageJson.version = version;
  writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(packageJson, null, 2)}\n`);
};

const updatePackageLock = (version) => {
  const packageLock = JSON.parse(readFileSync(PACKAGE_LOCK_PATH, 'utf8'));
  packageLock.version = version;
  if (packageLock.packages?.['']) {
    packageLock.packages[''].version = version;
  }
  writeFileSync(PACKAGE_LOCK_PATH, `${JSON.stringify(packageLock, null, 2)}\n`);
};

const updateReadme = (version) => {
  let readme = readFileSync(README_PATH, 'utf8');
  readme = readme.replace(
    /(https:\/\/img\.shields\.io\/badge\/version-)([\d.]+)(-blue\.svg)/,
    `$1${version}$3`
  );
  readme = readme.replace(/APP_VERSION=\d+\.\d+\.\d+/g, `APP_VERSION=${version}`);
  writeFileSync(README_PATH, readme);
};

const updateRuntimeProfiles = (version) => {
  const envFiles = readdirSync(ENV_DIR)
    .filter((file) => file.startsWith('.env') || file.endsWith('.env'))
    .map((file) => path.join(ENV_DIR, file));

  for (const filePath of envFiles) {
    const contents = readFileSync(filePath, 'utf8');
    const updated = contents.includes('APP_VERSION=')
      ? contents.replace(/APP_VERSION=.*$/gm, `APP_VERSION=${version}`)
      : `${contents.trimEnd()}\nAPP_VERSION=${version}\n`;
    writeFileSync(filePath, updated);
  }
};

const updateChangelog = ({ version, releaseTags }) => {
  const changelog = buildHistoricalChangelog({
    currentVersion: version,
    releaseTags
  });
  writeFileSync(CHANGELOG_PATH, changelog);
};

const releaseBase = resolveReleaseBase();
const commitEntries = getCommitLogEntries(releaseBase.baseRef);
const nextVersion = computeNextVersion({
  baseVersion: releaseBase.baseVersion,
  commitEntries
});

if (!nextVersion || !semverRegex.test(nextVersion)) {
  console.error(`Invalid version '${nextVersion}'. Expected semver x.y.z`);
  process.exit(1);
}

updatePackageJson(nextVersion);
updatePackageLock(nextVersion);
updateRuntimeProfiles(nextVersion);
updateReadme(nextVersion);
updateChangelog({
  version: nextVersion,
  releaseTags: releaseBase.releaseTags
});

console.log(`Version candidate set to ${nextVersion}`);

// Stage only the files the script owns so it cannot silently capture unrelated work.
runGit(['add', '--', 'package.json', 'package-lock.json', 'README.md', 'CHANGELOG.md', 'env']);

if (!hasStagedChanges()) {
  console.log('[set:version] No managed file changed; skipping commit.');
  process.exit(0);
}

runGit(['commit', '-m', `build(release): v${nextVersion}`]);
